---
name: Rotate keys
on:
  schedule: # Run every other month
    - cron: '0 11 1 */2 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context, for debugging
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

        # Rotate keys
      - name: Rotate Keys
        uses: ./action.yml
        with:
          # arn:aws:iam::179942336946:user/usc-rotate-keys-gha
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
